---
development:
  cloud_name: xxxxxxxxx
  api_key: 'xxxxxxxxx'
  api_secret: xxxxxxxxx
  enhance_image_tag: true
  static_file_support: false
  secure: true
  cdn_subdomain: true
production:
  cloud_name: xxxxxxxxx
  api_key: 'xxxxxxxxx'
  api_secret: xxxxxxxxx
  enhance_image_tag: true
  static_file_support: true
  secure: true
  cdn_subdomain: true
test:
  cloud_name: xxxxxxxxx
  api_key: 'xxxxxxxxx'
  api_secret: xxxxxxxxx
  enhance_image_tag: true
  static_file_support: false
